# demo configuration used by data_collection_single.py

collection_duration: 1200
sleep_time: 0.0
enable_MLX: 1
enable_realsense: 1
mi08_process: 0
mi16_process: 0
save: 1
# optional: if omitted, a timestamped folder under data/ will be used
save_dest: data/testing

exp_config_file: model3_m16
weights: "weights/m16/model3_m16_thermo_pt_0820152400.pth"
train: 0
thermal_input: m16
inference: 1
postprocess: 1
use_old_plot: 1

visualize: 1

use_recorded_data: 0
recorded_data_path: /home/zx/Desktop/zx/TAP3D_demo/data/testing