# demo configuration used by data_collection_single.py

collection_duration: 1200
sleep_time: 0.0
enable_MLX: 1
enable_realsense: 1
mi08_process: 0
mi16_process: 0
save: 0
# optional: if omitted, a timestamped folder under data/ will be used
save_dest: data/testing

exp_config_file: model3_seekthermal
weights: weights/seekthermal/model3_seekthermal_thermo_pt_0820225255.pth
train: 0
thermal_input: seek
inference: 1
postprocess: 0
use_old_plot: 1

visualize: 1

use_recorded_data: 0
recorded_data_path: MoreData/t20_m08_2