task: 'unet_seekthermal_init'
init_rand_seed: 41
tqdm_disable: False
tensorboard_folder: 'runs/seekthermal/'        
trained_model_folder: 'weights/seekthermal/'
model_save_enable: True
log_folder: 'logs/seekthermal/'
log_enable: True         
cuda_index: 0

num_epochs: 60
early_stop: 8 # the number of epochs to stop the training if the validation loss does not decrease
# batch_size: 256
# num_workers: 64
batch_size: 16
num_workers: 16
optimizer: 'AdamW' # 'AdamW', 'Lion' (https://github.com/lucidrains/lion-pytorch)
lr: 0.0005    # adamW: 0.001, Lion: 0.0004 (3-10x smaller than that for AdamW)
weight_decay: 0.004 # adamW: 0.004, Lion: 0.01  (Lion is 3-10x larger than that for AdamW)
momentum: 0.5

criterion: 'depthmask3C_loss' # corresponding to the label_type
metric: 'depthmask3C_metrics'  # corresponding to the label_type
depthmask_to_pointcloud: True # if True, we will convert the output the point cloud format and use pointcloud_metrics
detection_threshold: 0.5 # threshold for person detection confidence
point_threshold: 10 # 10mm
sensor_name: 'seek_thermal'
max_num_points: 1000
max_num_persons: 5
chunk_size: 1
preload: False
label_type: 'depth_mask_3C'  

model_name: 'unet_like'
out_channels: 3
init_features: 32


trainset_config_file: 'train0_small.yaml'
testset_config_file: 'test0_small.yaml'